[package]
name = "morse"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
morse-lib ={ path = "../morse-lib"}
# morse-lib ={ git = "https://github.com/NazarK0/morse-lib"}
